default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-54-195-252-243.eu-west-1.compute.amazonaws.com
  pool: 5
  database: d9fss0ntca25iv
  username: sfytwhvqbtpbzy
  password: 02e2971a48fdecdd4e67dc57def9cbb2fb438e83d13c3f0caa1d12c5b0968445
  port: 5432

development: &development
  <<: *default

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *development

preproduction:
  <<: *development

production:
  <<: *development

test:
  <<: *default
  database: consul_test
