default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-46-137-187-23.eu-west-1.compute.amazonaws.com
  pool: 5
  database: da0uu2v79gocns
  username: ymucnvmmgvzvlw
  password: cf29acd4255129de88d5d5d5ef5a0eaa3baf5c7e5c56aca01b6f442568a7280f
  port: 5432

development: &development
  <<: *default

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *development

preproduction:
  <<: *development

production:
  <<: *development

test:
  <<: *default
  database: consul_test
